### ISSUE TITLE
unexpected keyword argument 'capture_output'

### ISSUE THREAD

**Issue by mwxp06** [rmoesbergen/openwrt#1]
Hello,
I'm trying your solution for HA on my Turris router,
but have some issue:

`turris:~/scripts/device_tracker# python3 device.py 
Traceback (most recent call last):
  File "device.py", line 99, in <module>
    detector.polling_loop()
  File "device.py", line 80, in polling_loop
    process = subprocess.run(['ubus', 'call', interface, 'get_clients'], capture_output=True, text=True)
  File "/subprocess.py", line 423, in run
TypeError: __init__() got an unexpected keyword argument 'capture_output'`

**Comment by mwxp06** [comment]
Fixed is for older version python 3.5 and python 3.6 this:
`process = subprocess.run(['ubus', 'call', interface, 'get_clients'], stdout=subprocess.PIPE)
                if process.returncode == 0:
                    clients = json.loads(process.stdout)`

**Comment by rmoesbergen** [comment]
nice! If you can create a PR, I'll merge it..

**Comment by mwxp06** [comment]
This is only workaround for old version of python :)
Closing it :)
