### ISSUE TITLE
Clarification on full_sync_polls

### ISSUE THREAD

**Issue by Alf626** [rmoesbergen/openwrt#10]
Can you help me understand how "full_sync_polls" is supposed to work?

Your description seems to indicate that a full list of devices will be sent to HA every 2.5 minutes (using default values).

_full_sync_polls: Re-sync the device state of all devices every X poll intervals._

However, if I enable debug, I never see the "full sync" message in my logs.

Looking at the code, it appears that a resync may only be sent if "offline_after" is triggered.

To test, I restarted HA and after 15 minutes, my phone still shows as "not home".

If I change:

	```
      for client, offline_after in self._clients_seen.items():
        if offline_after == self._settings.offline_after:
          self._logger.log(f"full sync {client}", is_debug=True)
          ok &= self._ha_seen(client)
```
					
To:
	```
      for client, offline_after in self._clients_seen.items():
        self._logger.log(f"full sync fix {client}", is_debug=True)
        ok &= self._ha_seen(client)
```
        				
Within 3 minutes of rebooting HA, my phone shows as home.  However, I don't know what side effects this change may have.

**Comment by rmoesbergen** [comment]
Hi, thanks for the report. You've discovered a bug: the period full sync indeed doesn't work at the moment. I'll create a fix shortly.

**Comment by rmoesbergen** [comment]
I just pushed a fix. Please confirm if it's working for you.
