### ISSUE TITLE
I had to make these chages to make it work

### ISSUE THREAD

**Issue by brijins** [rmoesbergen/openwrt#11]
First of all, thank you for your effort! Other integrations didn't really work for me as well and was searching for alternatives. 

For some reason the device_tracker/see service was not working for me on HA 2022.9.1. I had to make the following changes to _ha_seen() to make it work, for the post call. Just putting it out here for reference in case if anybody else get stuck while setting it up. 

```
try:
    track_id = body['dev_id']
    body.update({'state': location})
    response = requests.post(
        f"{self._settings.hass_url}/api/states/device_tracker.{track_id}",
        json=body,
        headers={"Authorization": f"Bearer {self._settings.hass_token}"},
    )
    self._logger.log(f"API Response: {response.content!r}", is_debug=True)
except Exception as ex:
    self._logger.log(str(ex), is_debug=True)
    # Force full sync when HA returns
    self._full_sync_counter = 0
    return False
```

**Comment by rmoesbergen** [comment]
Hi @brijins , I guess this depends on the type of device being tracked. Did you create a `device_tracker:` entry for this device in your home assistant configuration.yaml? I run 2022.9.4 and the device_tracer/see service work fine for me.

**Comment by brijins** [comment]
Hi @rmoesbergen, Oh I did not do that part, I was strictly following the README.. would it be possible to add those steps as well to your instructions?

**Comment by rmoesbergen** [comment]
Oh, I meant to ask if you have manually configured devices, but I guess you don't. Interesting... do you use `default_config:` in your ha configuration.yaml? If not perhaps the component that provides the 'see' service is not loaded. Otherwise I'd be very interested in the HTTP response you get from the device_tracker/see call when it fails.

**Comment by brijins** [comment]
Nope, I didn't create any. 

here is my default_config: (yes I think you are right..)
```
# Loads default set of integrations. Do not remove.
default_config:
   alexa_media:
      accounts:
         email: !secret amazon_email
         password: !secret amazon_pass
         url: ***
```

This is the response I received from HA. 
```
>>> body = {"mac": "***", "location_name": "home", "source_type": "router", "hostname":"Brijin", "dev_id": "brijin_phone"}
>>> response = requests.post("http://192.168.50.56:8123/api/services/device_tracker/see", json=body, headers=headers)
>>> response.content
b'[]'
```

**Comment by rmoesbergen** [comment]
Ok, so that works. But what if you leave out the 'dev_id' field in the request? Because I currently don't include that field in the call to the 'see' service.

**Comment by rmoesbergen** [comment]
@brijins Instead of modifying the code, you could add this to your settings:

```
  "params": {
    "<your device mac address>": {
      "dev_id": "brijin_phone"
    }
  },
```

I guess this is needed if the device is not created by the device_tracker service, but by some other HA component like the Android/IOS app for example.
