### ISSUE TITLE
RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by Karl483r** [rmoesbergen/openwrt#13]
Hi, 
thanks for your script, most of the time it works perfectly!

From time to time I get this exception:
```root@OpenWrt:/etc/config# python3 presence-detector.py
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 980, in _bootstrap_inner
  File "/etc/config/presence-detector.py", line 198, in run
    self.full_sync()
  File "/etc/config/presence-detector.py", line 108, in full_sync
    for client, offline_after in self._clients_seen.items():
RuntimeError: dictionary changed size during iteration
```

Any idea how to fix that?

Thanks!

**Comment by rmoesbergen** [comment]
@Karl483r Thanks for the report! Should be fixed in 'main'. Can you confirm this works? I'll do a release once we're sure the bug is fixed.

**Comment by Karl483r** [comment]
Thank you! I will try the fix and report back. But could take a few days, as the error only occurs occasionally.

**Comment by Karl483r** [comment]
So far everything works fine! Thank you!

**Comment by rmoesbergen** [comment]
Nice :) I'll create a release. Thanks for reporting back!
