### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by whxciotw** [rmoesbergen/openwrt#7]
I have Installed python + deps: opkg update && opkg install python3-requests, but the logs still show the error as below:
`Sat Aug 14 23:00:41 2021 daemon.err presence-detector.py[25988]: Traceback (most recent call last):
Sat Aug 14 23:00:41 2021 daemon.err presence-detector.py[25988]:   File "/etc/config/presence-detector.py", line 5, in <module>
Sat Aug 14 23:00:41 2021 daemon.err presence-detector.py[25988]:     import requests
Sat Aug 14 23:00:41 2021 daemon.err presence-detector.py[25988]: ModuleNotFoundError: No module named 'requests'`

**Comment by rmoesbergen** [comment]
@whxciotw That's interesting... it seems the installation of the requests module either didn't succeed, or it is installed in a location where python doesn't look for modules. If you run presence-detector 'interactively' (meaning by hand in a terminal), does it work then?
