### ISSUE TITLE
No module named 'requests'

### ISSUE THREAD

**Issue by janvandijk96** [rmoesbergen/openwrt#8]
`Tue Mar 29 18:23:38 2022 daemon.err presence-detector.py[19483]: Traceback (most recent call last):`
`Tue Mar 29 18:23:38 2022 daemon.err presence-detector.py[19483]:   File "/etc/config/presence-detector.py", line 5, in <module>`
`Tue Mar 29 18:23:38 2022 daemon.err presence-detector.py[19483]:     import requests`
`Tue Mar 29 18:23:38 2022 daemon.err presence-detector.py[19483]: ModuleNotFoundError: No module named 'requests'`

Any idea how I can fix this? I've got the module installed, checked via package manager too:
`python3-requests	2.25.1-2`

I tried to install it manually too, but to no avail. Would like to make this work! :) 

Thanks a lot

**Comment by rmoesbergen** [comment]
@janvandijk96 Are you sure are starting python3? And if so, are you starting the same python3 that was used to installed the requests package? What happens if you start the script like this:
`python3 presence-detector.py`

**Comment by rmoesbergen** [comment]
no reply, closing this.
